# Generated by Django 4.0.8 on 2022-12-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment_cover_alter_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cover',
        ),
    ]
