# Generated by Django 4.0.8 on 2022-12-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_comment_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
